# Generated by Django 5.2.8 on 2025-11-21 18:19

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de actualización')),
                ('created_by', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Creado por')),
                ('updated_by', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Actualizado por')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Fecha de eliminación')),
                ('deleted_by', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Eliminado por')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de actualización')),
                ('created_by', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Creado por')),
                ('updated_by', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Actualizado por')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Fecha de eliminación')),
                ('deleted_by', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Eliminado por')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='api.company')),
                ('sales_rep', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de actualización')),
                ('created_by', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Creado por')),
                ('updated_by', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Actualizado por')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Fecha de eliminación')),
                ('deleted_by', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Eliminado por')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interaction_type', models.CharField(choices=[('Phone', 'Phone'), ('Email', 'Email'), ('SMS', 'SMS'), ('Facebook', 'Facebook')], max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='api.customer')),
                ('sales_rep', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['timestamp'], name='api_interac_timesta_270161_idx'), models.Index(fields=['interaction_type'], name='api_interac_interac_7c8cee_idx')],
            },
        ),
    ]
